### ISSUE TITLE
get_reputation_data in examples folder not working  

### ISSUE THREAD

**Issue by seyedsalar** [grokify/go-stackoverflow#24]
When I run [`main.go`](/grokify/go-stackoverflow/blob/e3040bd1f89be6216116f8aadd275a042f7106b6/examples/get_reputation_date/main.go) in [get_reputation_data](/grokify/go-stackoverflow/tree/master/examples/get_reputation_date) it shows "**400 Bad Request**" error, note that it works finely one week ago.

**Comment by grokify** [comment]
Could this have been a temporary server-side issue?

I wasn't able to reproduce your error and this still works for me.

Can you retry this?

I tried the following, which all run for me:

* `v0.1.4` (2022-06-08): 07ec46df0b121deac44d4782fd00541021e33e36
* latest for this ticket (2022-08-31): b719fbfe91bbe8f0930359cd5895d7729716fb4b
* `v0.1.5` (2022-10-29): f3bdde180911ee5769fb748af4d55635482e2b0f

**Comment by grokify** [comment]
Closing due to inability to reproduce and no response for over 7 days.

Please post if this surfaces again.
